In [1]:
import numpy as np

In [2]:
np.random.seed(42)

# Samples

In [3]:
X = np.array([[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]])

# As an Object

In [4]:
# the Dense Layer takes the batch size (num of samples) and the
# number of neurons, which we deside as we desire
# NOTE: the number of neurons effects the output's shape, 
# also the input of the next layer
class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.1 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [5]:
# assume X has 3 samples with 4 samples
layer1 = Layer_Dense(X.shape[1], 5)

In [6]:
layer2 = Layer_Dense(5, 2)

# Forward

In [7]:
layer1.forward(X)
print(layer1.output)

[[-0.27675317 -0.09091057  0.36940631 -0.74258198 -0.7854546 ]
 [-0.08384138  0.6059603   0.55190831  0.07959199  0.11448039]
 [-0.24566894  0.37446278  0.16476186 -0.91395312 -0.27462437]]


In [8]:
layer2.forward(layer1.output)
print(layer2.output)

[[ 0.07136211  0.01831101]
 [-0.05427832 -0.0786683 ]
 [ 0.07924331 -0.07230373]]
