In [1]:
import numpy as np

# Softmax

In [2]:
layer_outputs = [4.8, 1.12, 2.385]

In [15]:
exp_values = np.exp(layer_outputs)
exp_values

array([121.51041752,   3.0648542 ,  10.85906266])

In [16]:
# normalize with exponentials
normalized = []
norm_base = np.sum(exp_values)
for value in exp_values:
    normalized.append(value/norm_base)
normalized

[0.8971906427477128, 0.022629817004426896, 0.08017954024786043]

# As an Object

In [17]:
# as batches
layer_outputs = [[4.8, 1.12, 2.385],
                [8.9, -1.81, 0.2],
                [1.41, 1.051, 0.026]]

In [37]:
class Activation_Softmax:
    def __init__(self, inputs, n_neurons):
        self.weights = np.exp(layer_outputs)
        
        # keepdims -> keeps the dimensions as the same as before
        self.norm_base = np.sum(self.weights, axis=1, keepdims=True)
        self.weights = self.weights / self.norm_base
        
        
    def forward(self, inputs):
        pass

In [38]:
softmax_layer = Activation_Softmax(layer_outputs, 5)

In [39]:
softmax_layer.weights

array([[8.97190643e-01, 2.26298170e-02, 8.01795402e-02],
       [9.99811129e-01, 2.23163963e-05, 1.66554348e-04],
       [5.13097164e-01, 3.58333899e-01, 1.28568936e-01]])

In [40]:
softmax_layer.norm_base

array([[ 135.43433439],
       [7333.35859605],
       [   7.98280655]])